FROM --platform=$BUILDPLATFORM golang:1.21-alpine AS build

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build

FROM alpine:3.18

ARG GENESIS_BUILD_VERSION
ARG GENESIS_BUILD_DATE
ARG GENESIS_BUILD_COMMIT

WORKDIR /app

COPY --from=build /app/genesis /app

EXPOSE 8080

ENV GENESIS_BUILD_VERSION=${GENESIS_BUILD_VERSION}
ENV GENESIS_BUILD_DATE=${GENESIS_BUILD_DATE}
ENV GENESIS_BUILD_COMMIT=${GENESIS_BUILD_COMMIT}

CMD ["./genesis"]
